@startuml Parser

package Parser {
	class Launch {
		helpPDFtoFiles():void
		checkFolderExist():boolean
		checkOption(String):boolean
		setupOptions():void
		finishMessage():void
	}

	class PdfToPlainText {
		currentFile:String
		manager:FileManager
		doc:File
		---
		DEBUG_TEXT:boolean
		DEBUG_TITLE:boolean
		DEBUG_AUTHOR:boolean
		DEBUG_EMAIL:boolean
		DEBUG_ABSTRACT:boolean
		DEBUG_REFERENCE:boolean
		---
		filename:String
		title:String
		authors:String[]
		emails:String[]
		abstract:String
		references:String[]
		fileProcessing(String):void
		resetCoreVariables():void
		getTextFirstPage():String
		getTextLastPage():String
		getTextAnyPage(int):String
		getNbPages():int
		getMetadata():void
		__setFilename():void
		__setTitle(HashMap[], String):void
		__findEmails(String):boolean
		__setAuthorsAndEmails(String):void
		getAuthorsFromEmails():void
		__setAbstract(String):void
		__setReferences(String):void
	}

	class FileManager {
		OS_NAME:boolean
		folder:String
		resFolder:String
		files:String[]
		createResultFolder():void
		openFile(String):file
		getFileName(String):String
		writeTXT(String):void
		writeXML(String):void
	}

	package ToFormat {
		class toTXT{
			folder:String
			files:String[]
			manager:FileManager
			pdfTPT:pdfToPlainText
			allPDF(int):void
		}
	
		class ToXML{
			folder:String
			files:String[]
			manager:FileManager
			pdfTPT:pdfToPlainText
			allPDF(int):void
		}
	}

	package Utils {
		enum textmanipulation {
			REGEX_TITLE
			REGEX_MULTI_EMAILS
			REGEX_ABSTRACT
			REGEX_NO_ABSTRACT
			REGEX_REFERENCES
			REGEX_TABREFERENCES
			preCleanText(String):String
			pasCleanText(String):String
			allClean(String):String
			authorFormat():String[]
			cleanEmails(String[]):String[]
			arrangeTXT(PdfToPlainText):String
			arrangeXML(PdfToPlainText):String
		}

		class ProgressBar {
			total_index:int
			progress(int):void
		}
	}
}

Launch .> ToFormat : FOLDER
ToXML .> FileManager : FOLDER
ToXML.> PdfToPlainText : file
ToXML .> textmanipulation : PdfToPlainText
FileManager .> ToXML : files[]
PdfToPlainText .> textmanipulation : String

hide Launch circle

@enduml